### PR TITLE
Make build and publish different tasks

### PR DESCRIPTION
**Pull request by RDIL**
Easier for contributors

### CODE REVIEW

**Comment by RDIL** [comment]
oh also @N8python you have your git configured wrong

```bash
git config --global user.name "Nathan Breslow" && git config --global user.email "your-email@gmail.com"
```

**Review by N8python — CHANGES_REQUESTED** [review]
I like what you've done here - thx! However, I use the name N8 when authoring NPM packages, if you could change it back that would be great. Thx!

**Comment by N8python** [comment]
Ok - I'm going ahead and merging it!

**Comment by RDIL** [comment]
also @N8python can I have an org invite so I can transfer the docker container repo here

**Comment by N8python** [comment]
Sure, I'll give you readonly + suggesting access.

**Pull request merged**
